### PR TITLE
Pdf generation improvements

### PR DESCRIPTION
**Pull request by crisjdiaz**
We can use the variables -Drepo=repository_name and -Dpage=index_page_name when execute maven package goal.
Title added to pdf front-page.

### CODE REVIEW

**Comment by may-bee** [comment]
Please start developing on a development branch.
We currently have different jenkins jobs generating documents with the docgen approach.

After this merge, you broke the builds:

```
[INFO] --- docbkx-maven-plugin:2.0.15:generate-pdf (pdf) @ devonfw-docgen ---
[INFO] Processing input file: OASP4Mobile.xml
Error on line 119 column 10 of file:/var/lib/tomcat7/webapps/jenkins/jobs/oasp4mobile-tukl-wiki/workspace/devonfw-docgen/src/main/docbook/xsl/pdf.xsl:
  Error reported by XML parser: The string "--" is not permitted within comments.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.202s
[INFO] Finished at: Mon Jun 29 11:53:43 UTC 2015
[INFO] Final Memory: 30M/390M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.agilejava.docbkx:docbkx-maven-plugin:2.0.15:generate-pdf (pdf) on project devonfw-docgen: Execution pdf of goal com.agilejava.docbkx:docbkx-maven-plugin:2.0.15:generate-pdf failed: Failed to build Transformer from file:/var/lib/tomcat7/webapps/jenkins/jobs/oasp4mobile-tukl-wiki/workspace/devonfw-docgen/src/main/docbook/xsl/pdf.xsl: Failed to parse stylesheet -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by amarinso** [comment]
Completely my fault.

I thought nobody else was working with this repo and messed up with git merge.

I've fixed the error and created a new jenkins job with the new usage of parameters:

http://oasp-ci.cloudapp.net/jenkins/job/oasp4mobile-tukl-wiki--new-approach/lastSuccessfulBuild/artifact/devonfw-docgen/target/generated-docs/OASP4Mobile.pdf

And we will work on restoring your changes to get the proper PDF generation.

Next time we will be more cautious.

**Comment by may-bee** [comment]
Thanks :+1:, but until now, the title is gone or minimized, isn't it? :)

The devon wiki jobs are currently building against the master branch. Also CobiGen does the same.
Because of that, I think we should switch to a stable master and a development branch. Then everyone can choose in his jenkins job, whether he wants to have the lastest features or just the stable one.

**Comment by amarinso** [comment]
Yes. We are trying to fix the title now.

For the other documents an image logo is  used  and we have to combine both.

Forking the oasp docgen  was a hack to have it working quickly.we have to rethink a bit how to operate the docgen within  devonfw. We should duplicate the project instead of  forking for added flexibility

And working with master/develop braches  should also be the way to go

By the way, if this module is intended to be IP  we should rename it to devon4mobile   and have a custom logo in line with the devonfw  and devon sencha ones. Or will it be eventually  be released as open source ?

**Comment by may-bee** [comment]
Currently this project is just a project of students to evaluate the tool chain for mobile development.
We will decide what to the according to the results they will bring up and rename/move this appropriately.

**Pull request merged**
